channels_list = [
    'https://t.me/serbia_jobs',
    'https://t.me/progjob',
    'https://t.me/careerspace',
    'https://t.me/easy_python_job',
    'https://t.me/job_for_relocation',
    'https://t.me/remotegeekjob',
    'https://t.me/myjobit',
    'https://t.me/huggabletalents',
    'https://t.me/evacuatejobs',
    'https://t.me/zarubezhom_jobs',
    'https://t.me/vakansii_it',
    'https://t.me/yuniorapp',
    'https://t.me/devs_it',
    'https://t.me/workingincrypto',
    'https://t.me/jobforjunior',
    'https://t.me/geekjobs',
    'https://t.me/cyithr',
    'https://t.me/time2find',
    'https://t.me/it_vakansii_jobs',
    'https://t.me/yojob',
    'https://t.me/job_it_hunterxhunter',
    # '@remote',
    'https://t.me/rfoundersjobs',
    'https://t.me/hiring_ct',
    'https://t.me/hrexpert63_vacancies',
    'https://t.me/forpython',
    'https://t.me/careers_crypto',
    'https://t.me/young_relocate',
    'https://t.me/Remoteit',
    'https://t.me/Relocats',
    'https://t.me/it_vacancy_relocation',
    'https://t.me/choicy_work',
    'https://t.me/remote_jobs_relocate',
    'https://t.me/job_web3',
    'https://t.me/jobs_in_it_remoute',
    'https://t.me/jobfortm',
    'https://t.me/top_rel',
    # 'https://t.me/IT_REMOTE_PROJECTS',
    'https://t.me/headzio',
    'https://t.me/heddoworld',
    'https://t.me/Getitrussia',
    'https://t.me/pythonrabota',
    'https://t.me/montenegro_it_jobs',
    'https://t.me/jobGeeks',
    'https://t.me/abroadjbs',
    # 'https://t.me/Remote_Software_Developer_Jobs',
    'https://t.me/cchellowork',
    'https://t.me/Cvflow',
    'https://t.me/cryptoMjob',
    'https://t.me/hiddengurus',
    'https://t.me/young_relocate',
]

